# Generated by Django 2.2.4 on 2019-08-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_auto_20190827_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('feeds', 'feeds'), ('birds', 'birds'), ('medicines', 'medicines')], max_length=255)),
                ('amount', models.IntegerField(default=0, verbose_name='Amount (N)')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='birds',
            options={'verbose_name_plural': 'Birds'},
        ),
        migrations.AlterModelOptions(
            name='employers',
            options={'verbose_name_plural': 'Employers'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='birds',
            name='cost_per_bird',
            field=models.IntegerField(default=0, verbose_name='cost per bird (N)'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='salary',
            field=models.CharField(max_length=255, verbose_name='salary (N)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='selling_price',
            field=models.IntegerField(verbose_name='selling price (N)'),
        ),
    ]
