# Generated by Django 2.2.4 on 2019-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_auto_20190827_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
