# Generated by Django 2.2.4 on 2019-08-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_auto_20190827_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casualty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casualty_type', models.CharField(choices=[('death', 'death'), ('damage', 'damage')], max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('birds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.Birds')),
            ],
        ),
    ]
