# Generated by Django 2.2.4 on 2019-08-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0005_casualty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casualty',
        ),
    ]
