# Generated by Django 2.2.4 on 2019-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0009_auto_20191014_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
