# Generated by Django 2.2.4 on 2019-10-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0010_auto_20191014_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='birds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poultry.Birds'),
        ),
    ]
