# Generated by Django 2.2.4 on 2019-10-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0011_medicalreport_birds'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
