# Generated by Django 2.2.4 on 2019-10-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0012_casualty_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casualty',
            name='description',
        ),
    ]
