# Generated by Django 2.2.4 on 2019-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0013_remove_casualty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
