# Generated by Django 2.2.4 on 2019-10-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0014_auto_20191014_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('birds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.Birds')),
            ],
        ),
    ]
